language: node_js
node_js:
  - stable

cache: yarn

script:
  - yarn clean
  - yarn lint
  - yarn test:coverage
  - yarn build


deploy:
  provider: script
  script: yarn deploy
  skip_cleanup: true
  on:
    branch: develop
